// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuNtGxSoQ00iJsqKLS2ZUGt6tqF1Nde9c',
    appId: '1:692882448192:web:9225c0318afb2c9e5a64a5',
    messagingSenderId: '692882448192',
    projectId: 'twitter-like-84745',
    authDomain: 'twitter-like-84745.firebaseapp.com',
    storageBucket: 'twitter-like-84745.firebasestorage.app',
    measurementId: 'G-P839P85KSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeurOyhKn2LLsVZUL3C9xLg_gHle7q21Q',
    appId: '1:692882448192:android:ecd3678b4b84e8745a64a5',
    messagingSenderId: '692882448192',
    projectId: 'twitter-like-84745',
    storageBucket: 'twitter-like-84745.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR3Xn9me6k2EWU1Ew12pAnUeWci9kMLQU',
    appId: '1:692882448192:ios:80c9bb148172cf9d5a64a5',
    messagingSenderId: '692882448192',
    projectId: 'twitter-like-84745',
    storageBucket: 'twitter-like-84745.firebasestorage.app',
    iosBundleId: 'com.example.twitter',
  );
}
